In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
train_data=pd.read_csv('train2.csv')
test_data=pd.read_csv('test2.csv')

In [3]:
train_data.head()

Id      v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
0  ID_279628684  190000.0       0      3       0     1       1     0    NaN   
1  ID_f29eb3ddd  135000.0       0      4       0     1       1     1    1.0   
2  ID_68de51c94       NaN       0      8       0     1       1     0    NaN   
3  ID_d671db89c  180000.0       0      5       0     1       1     1    1.0   
4  ID_d56d6f5f5  180000.0       0      5       0     1       1     1    1.0   

   r4h1  ...  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  SQBhogar_nin  \
0     0  ...          100    1849               1        100             0   
1     0  ...          144    4489               1        144             0   
2     0  ...          121    8464               1          0             0   
3     0  ...           81     289              16        121             4   
4     0  ...          121    1369              16        121             4   

   SQBovercrowding  SQBdependency  SQBmeaned  agesq  Target  
0         1.000000            0.0      100.0   1849       4  
1         1.000000           64.0      144.0   4489       4  
2         0.250000           64.0      121.0   8464       4  
3         1.777778            1.0      121.0    289       4  
4         1.777778            1.0      121.0   1369       4  

[5 rows x 143 columns]

In [4]:
test_data.head()

Id      v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
0  ID_2f6873615       NaN       0      5       0     1       1     0    NaN   
1  ID_1c78846d2       NaN       0      5       0     1       1     0    NaN   
2  ID_e5442cf6a       NaN       0      5       0     1       1     0    NaN   
3  ID_a8db26a79       NaN       0     14       0     1       1     1    1.0   
4  ID_a62966799  175000.0       0      4       0     1       1     1    1.0   

   r4h1  ...  age  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  \
0     1  ...    4            0      16               9          0   
1     1  ...   41          256    1681               9          0   
2     1  ...   41          289    1681               9          0   
3     0  ...   59          256    3481               1        256   
4     0  ...   18          121     324               1          0   

   SQBhogar_nin  SQBovercrowding  SQBdependency  SQBmeaned  agesq  
0             1             2.25           0.25     272.25     16  
1             1             2.25           0.25     272.25   1681  
2             1             2.25           0.25     272.25   1681  
3             0             1.00           0.00     256.00   3481  
4             1             0.25          64.00        NaN    324  

[5 rows x 142 columns]

In [5]:
#Identify the output variable.
for i in train_data.columns:
    if i not in test_data.columns:
        print("Our Target variable is {}".format(i))

Our Target variable is Target


In [6]:
#Here we can see that our output variable is "Target".

In [7]:
#Understand the type of data.
train_data.shape


(9557, 143)

In [8]:
test_data.shape

(23856, 142)

In [9]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9557 entries, 0 to 9556
Columns: 143 entries, Id to Target
dtypes: float64(8), int64(130), object(5)
memory usage: 10.4+ MB


In [10]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23856 entries, 0 to 23855
Columns: 142 entries, Id to agesq
dtypes: float64(8), int64(129), object(5)
memory usage: 25.8+ MB


In [11]:
train_data.describe()

v2a1       hacdor        rooms       hacapo         v14a  \
count  2.697000e+03  9557.000000  9557.000000  9557.000000  9557.000000   
mean   1.652316e+05     0.038087     4.955530     0.023648     0.994768   
std    1.504571e+05     0.191417     1.468381     0.151957     0.072145   
min    0.000000e+00     0.000000     1.000000     0.000000     0.000000   
25%    8.000000e+04     0.000000     4.000000     0.000000     1.000000   
50%    1.300000e+05     0.000000     5.000000     0.000000     1.000000   
75%    2.000000e+05     0.000000     6.000000     0.000000     1.000000   
max    2.353477e+06     1.000000    11.000000     1.000000     1.000000   

            refrig         v18q        v18q1         r4h1         r4h2  ...  \
count  9557.000000  9557.000000  2215.000000  9557.000000  9557.000000  ...   
mean      0.957623     0.231767     1.404063     0.385895     1.559171  ...   
std       0.201459     0.421983     0.763131     0.680779     1.036574  ...   
min       0.000000     0.000000     1.000000     0.000000     0.000000  ...   
25%       1.000000     0.000000     1.000000     0.000000     1.000000  ...   
50%       1.000000     0.000000     1.000000     0.000000     1.000000  ...   
75%       1.000000     0.000000     2.000000     1.000000     2.000000  ...   
max       1.000000     1.000000     6.000000     5.000000     8.000000  ...   

       SQBescolari       SQBage  SQBhogar_total    SQBedjefe  SQBhogar_nin  \
count  9557.000000  9557.000000     9557.000000  9557.000000   9557.000000   
mean     74.222769  1643.774302       19.132887    53.500262      3.844826   
std      76.777549  1741.197050       18.751395    78.445804      6.946296   
min       0.000000     0.000000        1.000000     0.000000      0.000000   
25%      16.000000   289.000000        9.000000     0.000000      0.000000   
50%      36.000000   961.000000       16.000000    36.000000      1.000000   
75%     121.000000  2601.000000       25.000000    81.000000      4.000000   
max     441.000000  9409.000000      169.000000   441.000000     81.000000   

       SQBovercrowding  SQBdependency    SQBmeaned        agesq       Target  
count      9557.000000    9557.000000  9552.000000  9557.000000  9557.000000  
mean          3.249485       3.900409   102.588867  1643.774302     3.302292  
std           4.129547      12.511831    93.516890  1741.197050     1.009565  
min           0.040000       0.000000     0.000000     0.000000     1.000000  
25%           1.000000       0.111111    36.000000   289.000000     3.000000  
50%           2.250000       0.444444    81.000000   961.000000     4.000000  
75%           4.000000       1.777778   134.560010  2601.000000     4.000000  
max          36.000000      64.000000  1369.000000  9409.000000     4.000000  

[8 rows x 138 columns]

In [12]:
test_data.describe()

v2a1        hacdor         rooms        hacapo          v14a  \
count  6.453000e+03  23856.000000  23856.000000  23856.000000  23856.000000   
mean   1.748726e+05      0.050679      4.955776      0.028421      0.992748   
std    1.567887e+05      0.219346      1.539753      0.166174      0.084850   
min    0.000000e+00      0.000000      1.000000      0.000000      0.000000   
25%    8.000000e+04      0.000000      4.000000      0.000000      1.000000   
50%    1.400000e+05      0.000000      5.000000      0.000000      1.000000   
75%    2.200000e+05      0.000000      6.000000      0.000000      1.000000   
max    2.852700e+06      1.000000     15.000000      1.000000      1.000000   

             refrig          v18q        v18q1          r4h1          r4h2  \
count  23856.000000  23856.000000  5730.000000  23856.000000  23856.000000   
mean       0.961603      0.240191     1.348517      0.416541      1.563967   
std        0.192157      0.427208     0.694216      0.713255      0.990171   
min        0.000000      0.000000     1.000000      0.000000      0.000000   
25%        1.000000      0.000000     1.000000      0.000000      1.000000   
50%        1.000000      0.000000     1.000000      0.000000      1.000000   
75%        1.000000      0.000000     1.750000      1.000000      2.000000   
max        1.000000      1.000000     6.000000      6.000000      7.000000   

       ...           age  SQBescolari        SQBage  SQBhogar_total  \
count  ...  23856.000000  23856.00000  23856.000000    23856.000000   
mean   ...     34.454183     74.44974   1657.798080       19.113389   
std    ...     21.696245     76.99701   1753.603406       17.314597   
min    ...      0.000000      0.00000      0.000000        1.000000   
25%    ...     16.000000     16.00000    256.000000        9.000000   
50%    ...     32.000000     36.00000   1024.000000       16.000000   
75%    ...     51.000000    121.00000   2601.000000       25.000000   
max    ...     97.000000    441.00000   9409.000000      169.000000   

          SQBedjefe  SQBhogar_nin  SQBovercrowding  SQBdependency  \
count  23856.000000  23856.000000     23856.000000   23856.000000   
mean      54.087232      3.885480         3.564751       4.171669   
std       77.312255      6.878967         6.668757      13.105989   
min        0.000000      0.000000         0.020408       0.000000   
25%        0.000000      0.000000         1.000000       0.111111   
50%       36.000000      1.000000         2.250000       0.444444   
75%       81.000000      4.000000         4.000000       1.777778   
max      441.000000    100.000000       169.000000      64.000000   

          SQBmeaned         agesq  
count  23825.000000  23856.000000  
mean     100.509220   1657.798080  
std       89.211063   1753.603406  
min        0.000000      0.000000  
25%       36.000000    256.000000  
50%       75.111115   1024.000000  
75%      132.250000   2601.000000  
max     1296.000000   9409.000000  

[8 rows x 137 columns]

In [13]:
target=train_data["Target"]

In [14]:
target

0       4
1       4
2       4
3       4
4       4
       ..
9552    2
9553    2
9554    2
9555    2
9556    2
Name: Target, Length: 9557, dtype: int64

In [15]:
target.unique()

array([4, 2, 3, 1])

In [16]:
print(train_data.dtypes.value_counts())

int64      130
float64      8
object       5
dtype: int64


In [17]:
for i in train_data.columns:
    a=train_data[i].dtype
    if a == 'object':
        print(i)

Id
idhogar
dependency
edjefe
edjefa


In [18]:
# lets drop Id and idhogar variable.

train_data.drop(['Id','idhogar'],axis=1,inplace=True)

In [19]:
for i in train_data.columns:
    a=train_data[i].dtype
    if a == 'object':
        print(i)

dependency
edjefe
edjefa


In [21]:
train_data['dependency'].value_counts()

yes          2192
no           1747
.5           1497
2             730
1.5           713
.33333334     598
.66666669     487
8             378
.25           260
3             236
4             100
.75            98
.2             90
1.3333334      84
.40000001      84
2.5            77
5              24
.80000001      18
1.25           18
3.5            18
2.25           13
.71428573      12
1.75           11
.83333331      11
.22222222      11
1.2            11
.2857143        9
1.6666666       8
.60000002       8
6               7
.16666667       7
Name: dependency, dtype: int64

In [22]:
#Now we convert the object to numeric data
def map(i):
    
    if i=='yes':
        return(float(1))
    elif i=='no':
        return(float(0))
    else:
        return(float(i))

In [23]:
train_data['dependency']=train_data['dependency'].apply(map)

In [24]:
for i in train_data.columns:
    a=train_data[i].dtype
    if a == 'object':
        print(i)

edjefe
edjefa


In [25]:
train_data['edjefe']=train_data['edjefe'].apply(map)
train_data['edjefa']=train_data['edjefa'].apply(map)

In [26]:
print(train_data.dtypes.value_counts())

int64      130
float64     11
dtype: int64


In [27]:
#Check if there is a house without a family head.
train_data.parentesco1.value_counts()

0    6584
1    2973
Name: parentesco1, dtype: int64

In [29]:
pd.crosstab(train_data['edjefa'],train_data['edjefe'])

edjefe  0.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0   ...  12.0  \
edjefa                                                              ...         
0.0      435   123   194   307   137   222  1845   234   257   486  ...   113   
1.0       69     0     0     0     0     0     0     0     0     0  ...     0   
2.0       84     0     0     0     0     0     0     0     0     0  ...     0   
3.0      152     0     0     0     0     0     0     0     0     0  ...     0   
4.0      136     0     0     0     0     0     0     0     0     0  ...     0   
5.0      176     0     0     0     0     0     0     0     0     0  ...     0   
6.0      947     0     0     0     0     0     0     0     0     0  ...     0   
7.0      179     0     0     0     0     0     0     0     0     0  ...     0   
8.0      217     0     0     0     0     0     0     0     0     0  ...     0   
9.0      237     0     0     0     0     0     0     0     0     0  ...     0   
10.0      96     0     0     0     0     0     0     0     0     0  ...     0   
11.0     399     0     0     0     0     0     0     0     0     0  ...     0   
12.0      72     0     0     0     0     0     0     0     0     0  ...     0   
13.0      52     0     0     0     0     0     0     0     0     0  ...     0   
14.0     120     0     0     0     0     0     0     0     0     0  ...     0   
15.0     188     0     0     0     0     0     0     0     0     0  ...     0   
16.0     113     0     0     0     0     0     0     0     0     0  ...     0   
17.0      76     0     0     0     0     0     0     0     0     0  ...     0   
18.0       3     0     0     0     0     0     0     0     0     0  ...     0   
19.0       4     0     0     0     0     0     0     0     0     0  ...     0   
20.0       2     0     0     0     0     0     0     0     0     0  ...     0   
21.0       5     0     0     0     0     0     0     0     0     0  ...     0   

edjefe  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0  21.0  
edjefa                                                        
0.0      103   208   285   134   202    19    14     7    43  
1.0        0     0     0     0     0     0     0     0     0  
2.0        0     0     0     0     0     0     0     0     0  
3.0        0     0     0     0     0     0     0     0     0  
4.0        0     0     0     0     0     0     0     0     0  
5.0        0     0     0     0     0     0     0     0     0  
6.0        0     0     0     0     0     0     0     0     0  
7.0        0     0     0     0     0     0     0     0     0  
8.0        0     0     0     0     0     0     0     0     0  
9.0        0     0     0     0     0     0     0     0     0  
10.0       0     0     0     0     0     0     0     0     0  
11.0       0     0     0     0     0     0     0     0     0  
12.0       0     0     0     0     0     0     0     0     0  
13.0       0     0     0     0     0     0     0     0     0  
14.0       0     0     0     0     0     0     0     0     0  
15.0       0     0     0     0     0     0     0     0     0  
16.0       0     0     0     0     0     0     0     0     0  
17.0       0     0     0     0     0     0     0     0     0  
18.0       0     0     0     0     0     0     0     0     0  
19.0       0     0     0     0     0     0     0     0     0  
20.0       0     0     0     0     0     0     0     0     0  
21.0       0     0     0     0     0     0     0     0     0  

[22 rows x 22 columns]

In [30]:
#From the above cross tab it is evident that there are 435 families with no family head.

In [31]:
#Set poverty level of the members and the head of the house within a family.
# Let us consider this on the basis of the rent paid
Poverty_level=train_data[train_data['v2a1'] !=0]
Poverty_level.shape

(9528, 141)

In [32]:
Poverty_level_1=Poverty_level.groupby('area1')['v2a1'].apply(np.median)

In [33]:
Poverty_level_1

area1
0   NaN
1   NaN
Name: v2a1, dtype: float64

In [34]:
train_data['v2a1'].fillna(0,inplace=True)

In [35]:
Poverty_level=train_data[train_data['v2a1'] !=0]
Poverty_level.shape
Poverty_level_2=Poverty_level.groupby('area1')['v2a1'].apply(np.median)

In [36]:
Poverty_level_2

area1
0     80000.0
1    140000.0
Name: v2a1, dtype: float64

In [38]:
def poverty(x):
    if x<8000:
        return('Below poverty level')
    
    elif x>140000:
        return('Above poverty level')
    elif x<140000:
        return('Below poverty level: Ur-ban ; Above poverty level : Rural ')

In [39]:
eg=Poverty_level['v2a1'].apply(poverty)

In [40]:
eg.shape

(2668,)

In [41]:
pd.crosstab(eg,Poverty_level['area1'])

area1                                                 0     1
v2a1                                                         
Above poverty level                                 139  1103
Below poverty level: Ur-ban ; Above poverty lev...  306  1081

In [42]:
#Count how many null values are existing in columns.
train_data.isna().sum(axis=0)

v2a1               0
hacdor             0
rooms              0
hacapo             0
v14a               0
                  ..
SQBovercrowding    0
SQBdependency      0
SQBmeaned          5
agesq              0
Target             0
Length: 141, dtype: int64

In [43]:
train_data.isna().sum().value_counts()

0       137
5         2
7928      1
7342      1
dtype: int64

In [44]:
#Remove null value rows of the target variable.
train_data['Target'].isna().sum()

0

In [ ]:
#There is no null value in target variable

In [46]:
float_col=[]
for i in train_data.columns:
    a=train_data[i].dtype
    if a == 'float64':
        float_col.append(i)
print(float_col)

['v2a1', 'v18q1', 'rez_esc', 'dependency', 'edjefe', 'edjefa', 'meaneduc', 'overcrowding', 'SQBovercrowding', 'SQBdependency', 'SQBmeaned']


In [47]:
train_data[float_col].isna().sum()

v2a1                  0
v18q1              7342
rez_esc            7928
dependency            0
edjefe                0
edjefa                0
meaneduc              5
overcrowding          0
SQBovercrowding       0
SQBdependency         0
SQBmeaned             5
dtype: int64

In [48]:
train_data['v18q1'].fillna(0,inplace=True)

In [49]:
train_data.drop(['tipovivi3', 'v18q','rez_esc','elimbasu5'],axis=1,inplace=True)

In [52]:
train_data['meaneduc'].fillna(np.mean(train_data['meaneduc']),inplace=True)
train_data['SQBmeaned'].fillna(np.mean(train_data['SQBmeaned']),inplace=True)

In [53]:
train_data.isna().sum().value_counts()

0    137
dtype: int64

In [54]:
train_data.isna().sum(axis=0)

v2a1               0
hacdor             0
rooms              0
hacapo             0
v14a               0
                  ..
SQBovercrowding    0
SQBdependency      0
SQBmeaned          0
agesq              0
Target             0
Length: 137, dtype: int64

In [55]:
#Predict the accuracy using random forest classifier and Check the accuracy using random forest with cross validation.
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
X_data=train_data.drop('Target',axis=1)
Y_data=train_data.Target

In [56]:
X_data_col=X_data.columns

In [57]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
X_data_1=SS.fit_transform(X_data)
X_data_1=pd.DataFrame(X_data_1,columns=X_data_col)

In [58]:
X_train,X_test,Y_train,Y_test=train_test_split(X_data_1,Y_data,test_size=0.25,stratify=Y_data,random_state=0)

In [59]:
from sklearn.ensemble import RandomForestClassifier

In [60]:
classifier=RandomForestClassifier()

In [61]:
classifier.fit(X_train,Y_train)

RandomForestClassifier()

In [62]:
y_predict=classifier.predict(X_test)

In [63]:
from sklearn.metrics import accuracy_score


In [64]:
accuracy=accuracy_score(y_predict,Y_test)

In [65]:
print(accuracy)

0.9100418410041841


In [66]:
from sklearn.metrics import classification_report, confusion_matrix

In [67]:
print(classification_report(y_predict,Y_test))

              precision    recall  f1-score   support

           1       0.76      0.96      0.85       150
           2       0.83      0.89      0.86       375
           3       0.71      0.96      0.81       221
           4       0.99      0.90      0.94      1644

    accuracy                           0.91      2390
   macro avg       0.82      0.93      0.87      2390
weighted avg       0.92      0.91      0.91      2390



In [68]:
print(confusion_matrix(y_predict,Y_test))

[[ 144    4    1    1]
 [  19  333   14    9]
 [   0    3  213    5]
 [  26   59   74 1485]]


In [69]:
#Using above RandomForest Classifier we can predict with accuracy of 91%.